# Generated by Django 5.1.2 on 2024-11-29 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('graph', '0004_conversation_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_users', to='auth.group'),
        ),
    ]
